"""The fixed synthetic merchant catalogue used by the local demonstration."""

# ruff: noqa: E501

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DemoMerchant:
    merchant_id: str
    name: str
    sector: str
    login_id: str
    password: str
    story: str
    baseline_success_rate: float
    sdk_version: str
    methods: tuple[str, ...]
    platforms: tuple[str, ...]


_ROWS = (
    (
        "MRC-01",
        "StrideWorks India",
        "D2C footwear",
        "strideworks",
        "Stride#Demo01",
        "Checkout failures rise after a merchant SDK release",
        0.944,
        "4.8",
        ("upi", "card", "wallet"),
        ("web", "android"),
    ),
    (
        "MRC-02",
        "CloudNest SaaS",
        "B2B SaaS",
        "cloudnest",
        "Cloud#Demo02",
        "Recurring card mandates fail after expiry",
        0.931,
        "4.7",
        ("card", "mandate"),
        ("web",),
    ),
    (
        "MRC-03",
        "QuickBite Kitchens",
        "Food delivery",
        "quickbite",
        "Bite#Demo03",
        "UPI provider degradation shared across merchants",
        0.952,
        "4.7",
        ("upi", "card"),
        ("web", "android", "ios"),
    ),
    (
        "MRC-04",
        "EventOrbit",
        "Ticketing",
        "eventorbit",
        "Orbit#Demo04",
        "Flash-sale latency and capacity pressure",
        0.926,
        "4.7",
        ("upi", "card"),
        ("web", "android"),
    ),
    (
        "MRC-05",
        "LearnSpring",
        "Education",
        "learnspring",
        "Learn#Demo05",
        "OTP failures from an issuer cluster",
        0.938,
        "4.7",
        ("upi", "card", "netbanking"),
        ("web", "android"),
    ),
    (
        "MRC-06",
        "TripMango",
        "Travel",
        "tripmango",
        "Trip#Demo06",
        "International cards fail during 3DS authentication",
        0.918,
        "4.7",
        ("card", "upi"),
        ("web", "ios"),
    ),
    (
        "MRC-07",
        "MediCart",
        "Healthcare commerce",
        "medicart",
        "Medi#Demo07",
        "Risk rule rejects genuine payments",
        0.947,
        "4.7",
        ("upi", "card"),
        ("web", "android"),
    ),
    (
        "MRC-08",
        "GameGrid",
        "Gaming",
        "gamegrid",
        "Game#Demo08",
        "Wallet payment degradation",
        0.957,
        "4.7",
        ("wallet", "upi", "card"),
        ("android", "ios"),
    ),
    (
        "MRC-09",
        "HomeHue",
        "Home decor",
        "homehue",
        "Home#Demo09",
        "Checkout JavaScript error",
        0.942,
        "4.7",
        ("upi", "card"),
        ("web",),
    ),
    (
        "MRC-10",
        "UrbanRide",
        "Mobility",
        "urbanride",
        "Ride#Demo10",
        "Delayed webhooks make payments look pending",
        0.961,
        "4.7",
        ("upi", "card", "wallet"),
        ("android", "ios"),
    ),
    (
        "MRC-11",
        "FreshBasket",
        "Grocery",
        "freshbasket",
        "Fresh#Demo11",
        "Same UPI network incident as QuickBite",
        0.956,
        "4.7",
        ("upi", "card"),
        ("web", "android"),
    ),
    (
        "MRC-12",
        "StyleHarbor",
        "Fashion marketplace",
        "styleharbor",
        "Style#Demo12",
        "Coupon configuration breaks discounted checkouts",
        0.935,
        "4.7",
        ("upi", "card", "wallet"),
        ("web", "android"),
    ),
    (
        "MRC-13",
        "FitPulse",
        "Fitness subscription",
        "fitpulse",
        "Fit#Demo13",
        "Subscription mandate retry flow",
        0.928,
        "4.7",
        ("card", "mandate"),
        ("web", "ios"),
    ),
    (
        "MRC-14",
        "BookBridge",
        "Books",
        "bookbridge",
        "Books#Demo14",
        "Android-only UPI redirect failures",
        0.951,
        "4.7",
        ("upi", "card"),
        ("web", "android"),
    ),
    (
        "MRC-15",
        "CreatorDock",
        "Creator SaaS",
        "creatordock",
        "Creator#Demo15",
        "International issuer decline spike",
        0.923,
        "4.7",
        ("card", "upi"),
        ("web",),
    ),
    (
        "MRC-16",
        "PetPantry",
        "Pet supplies",
        "petpantry",
        "Pets#Demo16",
        "Payment-page latency after deployment",
        0.948,
        "4.7",
        ("upi", "card"),
        ("web", "android"),
    ),
    (
        "MRC-17",
        "EduTickets",
        "Exam bookings",
        "edutickets",
        "Exam#Demo17",
        "Demand surge plus issuer OTP degradation",
        0.929,
        "4.7",
        ("upi", "card"),
        ("web", "android"),
    ),
    (
        "MRC-18",
        "CraftLane",
        "Artisan marketplace",
        "craftlane",
        "Craft#Demo18",
        "Mobile-browser redirect regression",
        0.936,
        "4.7",
        ("upi", "card"),
        ("web", "android"),
    ),
    (
        "MRC-19",
        "HealthDesk",
        "Clinic SaaS",
        "healthdesk",
        "Clinic#Demo19",
        "Late successful authorization",
        0.958,
        "4.7",
        ("card", "upi"),
        ("web",),
    ),
    (
        "MRC-20",
        "NovaGadgets",
        "Electronics",
        "novagadgets",
        "Nova#Demo20",
        "Normal statistical variation; agents abstain",
        0.949,
        "4.7",
        ("upi", "card", "wallet"),
        ("web", "android"),
    ),
)


DEMO_MERCHANTS = tuple(
    DemoMerchant(
        merchant_id=merchant_id,
        name=name,
        sector=sector,
        login_id=f"{handle}@demo.revenuesre.local",
        password=password,
        story=story,
        baseline_success_rate=baseline,
        sdk_version=sdk_version,
        methods=methods,
        platforms=platforms,
    )
    for merchant_id, name, sector, handle, password, story, baseline, sdk_version, methods, platforms in _ROWS
)
